### ISSUE TITLE
Get Sensor values into InfluxDB

### ISSUE THREAD

**Issue by Mkay505** [Bouni/luxtronik#11]
It was not possible to install Luxtronik via HACS. So I have to manually transfer each (necessary) sensor value to the configuration.yaml. Which also makes this confusing.
That's how far it goes.

I just don't get the entities passed into the InfluxDB. These are simply not displayed. Is there a workaround.

last but not least:
And is someone kind enough to publish the sensor values ​​for the Luxtronik configuration.yaml here? then I prefer to throw out what I don't need. Thanks alot

**Comment by Bouni** [comment]
Hi,

what do you mean by "It was not possible to install Luxtronik via HACS"?
Did you get an error message or what happens?

Here are the relevant parts of my config:

```yaml

influxdb:
  host: localhost
  database: home_assistant
  username: home_assistant
  password: !secret influx_pw

luxtronik:
  host: "192.168.178.100"
  port: 8889

sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
```

```yaml
# sensors/heatpump.yaml
- platform: luxtronik
  scan_interval: 60
  sensors:
    - group: calculations
      id: ID_WEB_Temperatur_TVL
      friendly_name: Temperatur Vorlauf
    - group: calculations
      id: ID_WEB_Temperatur_TRL
      friendly_name: Temperatur Rücklauf

    - group: calculations
      id: ID_WEB_Temperatur_TRL_ext
      friendly_name: Temperatur Rücklauf Soll
    - group: calculations
      id: ID_WEB_Sollwert_TRL_HZ
      friendly_name: Temperatur Rücklauf Extern

    - group: calculations
      id: ID_WEB_Temperatur_THG
      friendly_name: Temperatur Heissgas

    - group: calculations
      id: ID_WEB_Temperatur_TA
      friendly_name: Aussentemperaturfühler

    - group: calculations
      id: ID_WEB_Mitteltemperatur
      friendly_name: Mitteltemperatur

    - group: calculations
      id: ID_WEB_Einst_BWS_akt
      friendly_name: Temperatur Brauchwasser Soll
    - group: calculations
      id: ID_WEB_Temperatur_TBW
      friendly_name: Temperatur Brauchwasser

    - group: calculations
      id: ID_WEB_Temperatur_TFB1
      friendly_name: Mischkreis 1 Vorlauf
    - group: calculations
      id: ID_WEB_Sollwert_TVL_MK1
      friendly_name: Mischkreis 1 Vorlauf Soll

    - group: calculations
      id: ID_WEB_Temperatur_TFB2
      friendly_name: Mischkreis 2 Vorlauf
    - group: calculations
      id: ID_WEB_Sollwert_TVL_MK2
      friendly_name: Mischkreis 2 Vorlauf Soll

    - group: calculations
      id: ID_WEB_Temperatur_TWE
      friendly_name: Fühler Wärmequelle Eingang
    - group: calculations
      id: ID_WEB_Temperatur_TWA
      friendly_name: Fühler Wärmequelle Ausgang

    - group: calculations
      id: ID_WEB_LIN_UH
      friendly_name: Überhitzung
    - group: calculations
      id: ID_WEB_LIN_UH_Soll
      friendly_name: Überhitzung Soll

    - group: calculations
      id: ID_WEB_LIN_HD
      friendly_name: Hochdruck
    - group: calculations
      id: ID_WEB_LIN_ND
      friendly_name: Niederdruck

    - group: parameters
      id: ID_Ba_Hz_akt
      friendly_name: Betriebsart Heizung
    - group: parameters
      id: ID_Ba_Bw_akt
      friendly_name: Betriebsart Brauchwasser
```

```yaml
# binary_sensors/heatpump.yaml

 - platform: luxtronik
  sensors:
    - group: calculations
      id: ID_WEB_ASDin
      friendly_name: Soledruck ausreichend
    - group: calculations
      id: ID_WEB_EVUin
      friendly_name: EVU Sperre
      invert: true
    - group: calculations
      id: ID_WEB_HDin
      friendly_name: Hochdruck OK
      invert: true
    - group: calculations
      id: ID_WEB_MOTin
      friendly_name: Motorschutz OK

    - group: calculations
      id: ID_WEB_BUPout
      friendly_name: Warmwasserumwälzpumpe
    - group: calculations
      id: ID_WEB_FP2out
      friendly_name: FBH Umwälzpumpe 2
    - group: calculations
      id: ID_WEB_HUPout
      friendly_name: Entladepumpe Heizkreis
    - group: calculations
      id: ID_WEB_MA1out
      friendly_name: Mischer 1 auf
    - group: calculations
      id: ID_WEB_MZ1out
      friendly_name: Mischer 1 zu
    - group: calculations
      id: ID_WEB_VBOout
      friendly_name: Brunnenwasserpumpe
    - group: calculations
      id: ID_WEB_VD1out
      friendly_name: Verdichter
    - group: calculations
      id: ID_WEB_ZIPout
      friendly_name: Zirkulationspumpe
    - group: calculations
      id: ID_WEB_ZUPout
      friendly_name: Zusatzumwälzpumpe
    - group: calculations
      id: ID_WEB_MA2out
      friendly_name: Mischer 2 auf
    - group: calculations
      id: ID_WEB_MZ2out
      friendly_name: Mischer 2 zu
```

Home Assistant writes all sensor values to influxdb, you do not need to configure anything there.
If the sensors show up in HA you shoud also see them in influxdb.
