### ISSUE TITLE
Unit of datatype Power missing

### ISSUE THREAD

**Issue by macrojames** [Bouni/luxtronik#12]
I am using the calculation "Heat_Output" and it doesn't show correctly in Home Assistant (Wrong graph, no unit of measurement)
I guess the "Power" Datatype should be defined in const.UNITS or DEVICE_CLASSES?
![heat](https://user-images.githubusercontent.com/482151/100860367-b6b23780-3490-11eb-97a8-9c5f763388e8.PNG)

**Comment by macrojames** [comment]
I just saw it's also missing on Frequencies with rpm.

**Comment by Bouni** [comment]
Sorry for the late reply, I need to look into this once I got some spare time 😓

**Comment by Cees-van-Beek** [comment]
I think this is caused because "Frequency" and "Power" are not available as "device_class" in Home Assistant.
But there is a possibility to customize an entity:
https://www.home-assistant.io/docs/configuration/customizing-devices/
This works well for me:
![Schermafdruk van 2021-02-10 15-51-12](https://user-images.githubusercontent.com/16610333/107526257-f5aee880-6bb7-11eb-9449-26471c5f27f4.png)

**Comment by remyderuysscher** [comment]
> 
> 
> I think this is caused because "Frequency" and "Power" are not available as "device_class" in Home Assistant.
> But there is a possibility to customize an entity:
> https://www.home-assistant.io/docs/configuration/customizing-devices/
> This works well for me:
> ![Schermafdruk van 2021-02-10 15-51-12](https://user-images.githubusercontent.com/16610333/107526257-f5aee880-6bb7-11eb-9449-26471c5f27f4.png)

@Cees-van-Beek Can you share the "Stooklijn verschuiving" code?

**Comment by Cees-van-Beek** [comment]
@remyderuysscher 
You must have installed the luxtronic custom component via HACS.
First you need to add the entity "ID_Einst_WK_akt" to the sensors (group parameters):
```
- platform: luxtronik
  scan_interval: 15
  sensors:
    - group: calculations
      id: ID_WEB_Temperatur_TVL
      friendly_name: Temperatuur Aanvoer
....
    - group: parameters
      id: ID_Einst_WK_akt
....
```
Next you make an input_number (configuration/helpers), slider, min -3, max 3, stepsize 0,1 (it works quite good!).

Then you make two automations:
```
#if value changes on the luxtronik input_number is adjusted
- alias: set input number verschuiving
  trigger:
    platform: state
    entity_id: luxtronik.ID_Einst_WK_akt
  action:
    service: input_number.set_value
    data: 
      entity_id: input_number.stooklijn_verschuiving
      value: "{{ states('luxtronik.ID_Einst_WK_akt') }}"

#if input_number is changed, the new value is sent to luxtronic
- alias: set stooklijn verschuiving op luxtronik
  trigger:
  - platform: state
    entity_id: input_number.stooklijn_verschuiving
  action:
    service: luxtronik.write
    data:
      parameter: ID_Einst_WK_akt
    data_template:
      value: '{{ trigger.to_state.state }}'
```
Success!
