### ISSUE TITLE
missing sensor and unit of operating hours

### ISSUE THREAD

**Issue by Boddl** [Bouni/luxtronik#13]
Hello Bouni, 
i currently have 2 problems with the luxtronik integration.
1. the sensor "ID_WEB_Temperatur_TRL" is not displayed, the log says the following
![image](https://user-images.githubusercontent.com/75801166/103634140-f7e1af80-4f46-11eb-98c2-4f1a3ce1fbda.png)

2. the operating hours are shown in seconds, there is a possibility to change them in hours?
![image](https://user-images.githubusercontent.com/75801166/103634361-3ecfa500-4f47-11eb-963e-099ce0c5c9b2.png)

i hope you can help me. thx

**Comment by Bouni** [comment]
Hi,

The first one is strange, `ID_WEB_Temperatur_TRL` is clearly available: https://github.com/Bouni/python-luxtronik/blob/master/luxtronik/calculations.py#L54

Can you post your config?

For the second one, you can use template sensors to convert the value: 

```
sensor:
  - platform: template
    sensors:
      verdichter_betriebsstunden_h:
        friendly_name: "Verdichter Betriebsstunden"
        unit_of_measurement: 'h'
        value_template: "{{ states("luxtronik.verdichter_betriebsstunden")|float / 3600 }}"
```

**Comment by Boddl** [comment]
here my configuration.yaml
![image](https://user-images.githubusercontent.com/75801166/103636360-26ad5500-4f4a-11eb-86cb-1cb4b56edcf6.png)

sensors/luxtronik/luxtronik.yaml
![image](https://user-images.githubusercontent.com/75801166/103636412-388ef800-4f4a-11eb-9fa6-41b319937065.png)

**Comment by Boddl** [comment]
the second works, but i have change - value_template: "{}" in value_template: '{}'

**Comment by Bouni** [comment]
How did you install the integration, using HACS?

I have almost the exact same config and it works fine for me 🤔 
```
  - platform: luxtronik
    scan_interval: 60
    sensors:
      - group: calculations
        id: ID_WEB_Temperatur_TVL
        friendly_name: Temperatur Vorlauf
      - group: calculations
        id: ID_WEB_Temperatur_TRL
        friendly_name: Temperatur Rücklauf
```

![image](https://user-images.githubusercontent.com/948965/103667856-bbc64300-4f76-11eb-9ce5-0f0a49e1e229.png)
