### ISSUE TITLE
Old Entity remains after renaming 'friendly_name'

### ISSUE THREAD

**Issue by buentead** [Bouni/luxtronik#40]
In a 1st step I insert the sensor as documented:
```
# Example configuration.yaml entry
sensor:
  - platform: luxtronik
    sensors:
      - group: calculations
        id: ID_WEB_Temperatur_TVL
        friendly_name: Temperature forerun
        icon: mdi:thermometer
```
Everything works fine. I changed the 'friendly_name' to the German equivalent:
```
[...]
      - group: calculations
        id: ID_WEB_Temperatur_TVL
        friendly_name: Temp Vorlauf
        icon: mdi:thermometer
```
After rebooting HA, the Entity with the German name showed up and was correct. However, the English entity entry still exists but isn't updated anymore.

This is my configuration:
```
version: core-2022.4.6
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.9.9
os_name: Linux
os_version: 5.10.103-v8
arch: aarch64
host_os: Home Assistant OS 7.6
update_channel: stable
supervisor_version: supervisor-2022.04.0
docker_version: 20.10.9
disk_total: 457.7 GB
disk_used: 7.8 GB
healthy: true
supported: true
board: rpi4-64
supervisor_api: ok
version_api: ok
installed_addons: File editor (5.3.3), Samba share (9.5.1), Terminal & SSH (9.3.0), Mosquitto broker (6.0.1), Node-RED (11.1.1)
```
