### ISSUE TITLE
Convert "Heat Amount" to "power consumption"

### ISSUE THREAD

**Issue by robotnikz** [Bouni/luxtronik#48]
Hello everyone,
is there are possibility to use the Heat Amount Sensor from the Luxtronik Integration divided by the JAZ (=Jahrearbeitszahl) = Real Power Consumption.
I think that would be the better use for the Energy Dashboard.

So for example:

17.000 kWh Heat Amount : 4,8 (JAZ) = ~3500kWh real power consumption

Possible? 
Thanks in advance guys and thank you very much for your awesome work!

**Comment by Bouni** [comment]
You can do that using a template sensor. Where do you get the JAZ from? Honestly I've never dived deep enough into the matter to understand what JAZ really means 😅

**Comment by Bouni** [comment]
See https://www.home-assistant.io/integrations/template/ for reference

Should look something like that (untested):

```yaml
template:
  - sensor:
      - name: "Real Power Consumption"
        unit_of_measurement: "kWh"
        state: >
          {% set heat_amount= states('sensor.heat_amount') | float %}
          {% set jaz= states('sensor.jaz') | float %}
          {{ (heat_amount / jaz) | round(1, default=0) }}
```
