### ISSUE TITLE
Error: [invert] is an invalid option for [sensor.luxtronik]

### ISSUE THREAD

**Issue by mfmayer** [Bouni/luxtronik#58]
ID_WEB_EVUin seems to be an inverted boolean signal, which I tried to invert with the mentioned option "invert: true":
```yaml
      - group: calculations
        id: ID_WEB_EVUin
        friendly_name: WP EVU Sperre
        invert: true
```

Unfortunately this doesn't seem to work and I'm always getting this error:
`ERROR (MainThread) [homeassistant.config] Invalid config for [sensor.luxtronik]: [invert] is an invalid option for [sensor.luxtronik].`

Luxtronic Version: 2022.12.02
Home Assistant Version: 2022.12.7

**Comment by mfmayer** [comment]
I've found the problem. Binary sensors must be added below `binary_sensor` property and not `sensor` property:

```yaml
binary_sensor:
  - platform: luxtronik
    sensors:
      - group: calculations
        id: ID_WEB_EVUin
        friendly_name: WP EVU Sperre
        invert: true
```
