### ISSUE TITLE
Set of the target hot water temperature not working. 

### ISSUE THREAD

**Issue by tunguskar** [Bouni/luxtronik#65]
the reading of the hot water temperature is pretty fine. But when I want to set it with:

```yaml
service: luxtronik.write
data:
  parameter: ID_Soll_BWS_akt
  value: "60.0"
```
The value does not change. Do I have to set anything on the heat pump?

**Comment by mkubu** [comment]
Could you pls share excerpt of config how do you read the value?

**Comment by tunguskar** [comment]
```yaml
- platform: luxtronik
  sensors:
    - group: calculations
      id: ID_WEB_Temperatur_TVL
      friendly_name: Vorlauftemperatur Heizkreis Ist
      icon: mdi:thermometer
    - group: calculations
      id: ID_WEB_Temperatur_TRL
      friendly_name: Rücklauftemperatur Heizkreis Ist
      icon: mdi:thermometer
    - group: calculations
      id: ID_WEB_Sollwert_TRL_HZ
      friendly_name: Rücklauftemperatur Heizkreis Soll
      icon: mdi:thermometer
    - group: calculations
      id: ID_WEB_Temperatur_TRL_ext
      friendly_name: Rücklauftemperatur Trennspeicher
      icon: mdi:thermometer
    - group: calculations
      id: ID_WEB_Temperatur_TBW
      friendly_name: Temperatur Warmwasser ist
      icon: mdi:thermometer
    - group: calculations
      id: ID_WEB_Einst_BWS_akt
      friendly_name: Temperatur Warmwasser Soll
      icon: mdi:thermometer

```
