### ISSUE TITLE
Sensors does not update

### ISSUE THREAD

**Issue by sim-san** [Bouni/luxtronik#84]
I add the this integration with the following comnfiguration:

```
luxtronik:
  host: 192.168.20.7
  port: 8889
```

```
sensor:
  - platform: luxtronik
    sensors:
      - group: visibilities
        id: ID_Visi_Temp_MK1_Vorlauf
        friendly_name: Mischkreis 1 Vorlauf
        icon: mdi:thermometer
```

The sensor appear in the list of entities, but with a constant value of `1`. And this value of the enity is not updated. The last update timestamp is the restart time of home assistant.

Further Information: I have also the intrgration from BenPru (https://github.com/BenPru/luxtronik) enabled. Is this a problem ?
