### ISSUE TITLE
Wrong Value

### ISSUE THREAD

**Issue by dmm1** [Bouni/luxtronik#9]
Hi, thanks for this integration but i can't get it to work for visibilities:

- platform: luxtronik
  sensors:
    - group: visibilities
      id: ID_Visi_Temp_BW_Ist
      friendly_name: Heizung Warmwasser IST
      icon: mdi:thermometer

only returns a "1" 

Do you have an idea?

**Comment by Bouni** [comment]
Yes, visibilities are only binary and as far as I can tell define if a value is visible in the GUI. 
What you want is:

```
- platform: luxtronik
  sensors:
    - group: calculations
      id: ID_WEB_Temperatur_TBW
      friendly_name: Heizung Warmwasser IST
      icon: mdi:thermometer
```
