### ISSUE TITLE
New Parameter will not be acceptet

### ISSUE THREAD

**Issue by colognebroker** [Bouni/luxtronik#92]
I need an aditional parameter in luxtronik2

ID_WEB_SEC_Qh_Soll

i tried to config in configuration.yaml
sensors:
 - platform: luxtronik2
    sensors:
       - group: calculations
            id: ID_WEB_SEC_Qh_Soll

but i do not find him after new loading the integration

Whats wrong ?

**Comment by Bouni** [comment]
I double tested and it works for my heatpump:

```sh
python -c "from luxtronik import Luxtronik; l = Luxtronik('192.168.0.123', 8889); value = l.calculations.get('ID_WEB_SEC_Qh_Soll'); print(value);"
```

This gives me `0.0`

Also, if I add this to my luxtronik config:

```yaml
- platform: luxtronik
  scan_interval: 60
  sensors:
    - group: calculations
      id: ID_WEB_SEC_Qh_Soll
```

and restart HA, I see the value in the developer tools

![Image](https://github.com/user-attachments/assets/76680d7e-8b4b-48a7-be9e-319d5aba6ad2)

Not sure if thats an issue caused by @BenPru s [luxtronik2](https://github.com/BenPru/luxtronik) integration that you use!?
